# Generated by Django 3.0.7 on 2020-06-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/')),
                ('is_best_seller', models.BooleanField()),
            ],
        ),
    ]
