# Generated by Django 3.0.7 on 2020-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200609_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_best_seller',
        ),
        migrations.AddField(
            model_name='course',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='platform',
            field=models.CharField(default='Eduonix', max_length=30),
        ),
    ]
