# Generated by Django 3.0.7 on 2020-06-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200610_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
