# Generated by Django 3.0.7 on 2020-06-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
