# Generated by Django 3.0.7 on 2020-06-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
