# Generated by Django 3.0.7 on 2020-06-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200610_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.CharField(default='0/0', max_length=5),
        ),
    ]
