# Generated by Django 3.0.7 on 2020-06-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200611_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='platform',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
