# Generated by Django 3.0.7 on 2020-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200613_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='media/'),
        ),
    ]
