# Generated by Django 3.0.7 on 2020-06-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200613_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='best_seller',
            field=models.BooleanField(),
        ),
    ]
