# Generated by Django 3.0.7 on 2020-06-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200613_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('DEVELOPMENT', 'development'), ('IT & SOFTWARE', 'it&software'), ('OFFICE & PRODUCTIVITY', 'office&productivity'), ('DESIGN & PHOTOGRAPHY', 'design&photography'), ('MARKETING & BUSINESS', 'marketing&business'), ('OTHERS', 'others')], default='others', max_length=21),
        ),
    ]
