# Generated by Django 3.0.7 on 2020-06-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Subscriber',
        ),
    ]
