# Generated by Django 3.0.7 on 2020-06-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20200617_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='affiliate_url',
            field=models.CharField(default='http://sh.st/st/d6a5442052674a5a7a657d0688a75caa/', max_length=256),
        ),
    ]
