# Generated by Django 3.0.7 on 2020-06-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20200619_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('NOT SET', 'not_set'), ('DEVELOPMENT', 'development'), ('IT & SOFTWARE', 'it&software'), ('OFFICE & PRODUCTIVITY', 'office&productivity'), ('DESIGN & PHOTOGRAPHY', 'design&photography'), ('MARKETING & BUSINESS', 'marketing&business'), ('OTHERS', 'others')], default='not_set', max_length=21),
        ),
    ]
