# Generated by Django 3.0.7 on 2020-06-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20200620_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='best_seller',
            field=models.BooleanField(null=True),
        ),
    ]
