# Generated by Django 3.0.7 on 2020-06-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20200620_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['platform']},
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
