# Generated by Django 3.0.7 on 2020-06-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20200621_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('offer', models.CharField(max_length=200)),
                ('coupon', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=30)),
                ('valid', models.BooleanField()),
            ],
        ),
    ]
