# Generated by Django 3.0.7 on 2020-06-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20200621_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(choices=[('NOT SET', 'not_set'), ('DEVELOPMENT', 'development'), ('IT & SOFTWARE', 'it&software'), ('OFFICE & PRODUCTIVITY', 'office&productivity'), ('DESIGN & PHOTOGRAPHY', 'design&photography'), ('MARKETING & BUSINESS', 'marketing&business'), ('OTHERS', 'others')], default='not_set', max_length=30),
        ),
    ]
