# Generated by Django 3.0.7 on 2020-06-23 13:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20200623_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('not_set', 'NOT SET'), ('development', 'DEVELOPMENT'), ('it&software', 'IT & SOFTWARE'), ('office&productivity', 'OFFICE & PRODUCTIVITY'), ('design&photography', 'DESIGN & PHOTOGRAPHY'), ('marketing&business', 'MARKETING & BUSINESS'), ('others', 'OTHERS')], default='not_set', max_length=21),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('not_set', 'NOT SET'), ('development', 'DEVELOPMENT'), ('it&software', 'IT & SOFTWARE'), ('office&productivity', 'OFFICE & PRODUCTIVITY'), ('design&photography', 'DESIGN & PHOTOGRAPHY'), ('marketing&business', 'MARKETING & BUSINESS'), ('others', 'OTHERS')], max_length=96),
        ),
    ]
