# Generated by Django 3.0.7 on 2020-06-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_auto_20200623_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(blank=True, max_length=5),
        ),
    ]
