# Generated by Django 3.0.7 on 2020-06-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20200624_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
