# Generated by Django 3.0.7 on 2020-06-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_auto_20200624_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='expired',
            field=models.BooleanField(default=True),
        ),
    ]
