# Generated by Django 3.0.7 on 2020-06-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_auto_20200624_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
