# Generated by Django 3.0.7 on 2020-06-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_auto_20200624_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
