# Generated by Django 3.0.7 on 2020-06-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_auto_20200624_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realdiscount',
            name='coupon',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='realdiscount',
            name='offer',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
