# Generated by Django 3.0.7 on 2020-06-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_auto_20200627_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realdiscount',
            name='coupon',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='realdiscount',
            name='offer',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
