# Generated by Django 3.0.7 on 2020-07-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_auto_20200627_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_encoded',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
