# Generated by Django 3.0.7 on 2020-07-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_course_name_encoded'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contents',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
