# Generated by Django 3.0.7 on 2020-07-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_course_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='contents',
            field=models.BinaryField(blank=True),
        ),
    ]
