# Generated by Django 3.0.7 on 2020-07-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_course_urlbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='course',
            name='urlbox',
        ),
        migrations.AddField(
            model_name='course',
            name='url_encoded',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
