# Generated by Django 3.0.7 on 2020-07-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_auto_20200728_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='url_encoded',
            new_name='name_base64',
        ),
    ]
