# Generated by Django 3.0.7 on 2020-08-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uploaded_by',
            field=models.CharField(default='Coupons Town', max_length=100),
        ),
    ]
