# Generated by Django 3.1 on 2020-08-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_auto_20200815_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name_encoded',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
